spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: # 추후 공지
    password: # 추후 공지
    url: # 추후 공지
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true